services:
  timewarrior:
    build: .
    ports:
      - "7005:7005"
    env_file:
      - .env
    volumes:
      - ./templates:/app/templates
      - ./static:/app/static
    restart: unless-stopped